### PR TITLE
Update DatePicker.js

### PR DESCRIPTION
**Pull request by aliazizi**
`onChange` props should call if text input changed and the value of it is valid.

### CODE REVIEW

**Comment by aliazizi** [comment]
I also add `onInputChange` event

**Comment by aliazizi** [comment]
the cursor position set to end of string if persiandigit is active.
So I add `persianDigits` props and also fix cursor position

**Comment by aliazizi** [comment]
Oh i'm sorry for that. I remove it.

**Comment by mberneti** [comment]
@aliazizi
Thank you for the contribution, I'll review your changesets soon.

**Pull request merged**
