### PR TITLE
remove font from library but added to docs

### PR DESCRIPTION
**Pull request by muhshahabipour**

### CODE REVIEW

**Comment by mberneti** [comment]
@muhshahabipour thank you for contribution.
So after that every one should add this style:
`.calendarContainer *,
.datepicker-input,
.calendarContainer .heading .title,
.calendarContainer .daysOfWeek>div,
.time-picker-container,
.rc-time-picker-input,
.rc-time-picker-panel-inner {
    font-family: $fontFamily;
} `
I know loading default fonts is not good at all, I'm looking for a way to add new feature for adding new custom font or disabling default fonts loading dynamically.

**Comment by muhshahabipour** [comment]
> So after that every one should add this style:
`.calendarContainer *, .datepicker-input, .calendarContainer .heading .title, .calendarContainer .daysOfWeek>div, .time-picker-container, .rc-time-picker-input, .rc-time-picker-panel-inner { font-family: $fontFamily; } `

okey. in next pull request add below code that users should use their default fonts. 

users code:
```
body {
    // font-family: $EVERY_CUSTOM_FONT_NAME;
}
```

library code:
```
.calendarContainer *, .datepicker-input{
    font-family: inherit;
}

```

**Comment by mberneti** [comment]
Great, I'll check it ASAP.

**Comment by mberneti** [comment]
@all-contributors please add @dadwic for design and code

**Pull request merged**
